version: "3.5"
networks:
  telemetry_collector_telemetry:
    external: true
services:
  influxdb:
    image: ${INFLUXDB_IMAGE}
    container_name: influxdb1.7
    restart: always
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - 9086:8086
    networks:
      - telemetry_collector_telemetry
    volumes:
      - ${INFLUX_CONFIG}:/etc/influxdb
      - ${INFLUX_DATA}:/var/lib/influxdb
      - ${INFLUX_CONFIG}/scripts:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=influxdb
      - INFLUXDB_ADMIN_PASSWORD=influxdb
